### ISSUE TITLE
error while computing score from QTL sumstats

### ISSUE THREAD

**Issue by SalimMegat** [douglasyao/mesc#3]
Hi, 

Thanks for the tool ! I am trying to compute exp score from methylation data but while its working for most of the genes it is throwing an error for some of them. I do not quite understand the issue with the ldsc script...Any idea of what might go wrong ? 

Thank you, 

Salim 

Read gene 589 of 2483 (589 of 2483 total): FAM229A
Read gene 590 of 2483 (590 of 2483 total): FAM41C
Read gene 591 of 2483 (591 of 2483 total): FAM43B
Read gene 592 of 2483 (592 of 2483 total): FAM71A
Read gene 593 of 2483 (593 of 2483 total): FAM72A
<= 10 SNPs around gene; skipping
Read gene 594 of 2483 (594 of 2483 total): FAM76A
Traceback (most recent call last):
  File "./run_mesc.py", line 244, in <module>
    ss.get_expression_scores(args)
  File "/Users/salim/Desktop/mesc/mesc/expscore_sumstat.py", line 227, in get_expression_scores
    herit = estimate_expression_cis_herit(ref_ld, frq, temp_gene_mat, ref_ld_indices)
  File "/Users/salim/Desktop/mesc/mesc/expscore_sumstat.py", line 132, in estimate_expression_cis_herit
    s(zscores['N']), M_annot, n_blocks=10)
  File "/Users/salim/Desktop/mesc/mesc/regressions_ldsc.py", line 346, in __init__
    slow=slow, step1_ii=step1_ii, old_weights=old_weights)
  File "/Users/salim/Desktop/mesc/mesc/regressions_ldsc.py", line 164, in __init__
    x_tot, w, N, M_tot, tot_agg, intercept)
  File "/Users/salim/Desktop/mesc/mesc/regressions_ldsc.py", line 495, in _update_weights
    return self.weights(ld, w_ld, N, M, hsq, intercept, ii)
  File "/Users/salim/Desktop/mesc/mesc/regressions_ldsc.py", line 531, in weights
    c = hsq * N / M
FloatingPointError: invalid value encountered in true_divide

**Comment by douglasyao** [comment]
Hi Salim, could you send me the command and summary statistic file that causes this error at douglasyao@g.harvard.edu? Thanks!

**Comment by SalimMegat** [comment]
Hi Douglas, 

Thank for the reply ! Here is the file that I am using for chromosome 4. I sub-sampled the file to first 2000th row for a matter of size. It will throw an error on CpG island 1413:
Read gene 1413 of 11890 (1413 of 11890 total): cg02741554
Traceback (most recent call last):
  File "./run_mesc.py", line 244, in <module>
    ss.get_expression_scores(args)
  File "/Users/salim/Desktop/mesc/mesc/expscore_sumstat.py", line 227, in get_expression_scores
    herit = estimate_expression_cis_herit(ref_ld, frq, temp_gene_mat, ref_ld_indices)
  File "/Users/salim/Desktop/mesc/mesc/expscore_sumstat.py", line 113, in estimate_expression_cis_herit
    start_snp = zscores['SNP'].values[i]
IndexError: index 15 is out of bounds for axis 0 with size 15

Analysis finished at Mon Oct  5 20:53:45 2020
Total time elapsed: 51.72s
Traceback (most recent call last):
  File "./run_mesc.py", line 244, in <module>
    ss.get_expression_scores(args)
  File "/Users/salim/Desktop/mesc/mesc/expscore_sumstat.py", line 227, in get_expression_scores
    herit = estimate_expression_cis_herit(ref_ld, frq, temp_gene_mat, ref_ld_indices)
  File "/Users/salim/Desktop/mesc/mesc/expscore_sumstat.py", line 113, in estimate_expression_cis_herit
    start_snp = zscores['SNP'].values[i]
IndexError: index 15 is out of bounds for axis 0 with size 15
 
Thank you for you help ! 

Best, 

Salim. 

[mQTL_chr4_sub.gz](https://github.com/douglasyao/mesc/files/5329519/mQTL_chr4_sub.gz)
